
title: CSS layouts - Grid workshop 2018
baseurl: "grid-workshop/" # the subpath of your site, e.g. /blog/

markdown: kramdown
permalink: :title/

navigation:
 - title: CSS layouts - Grid workshop 2018
   url: index.html

exclude: [
    'node_modules',
    'bower_components',
    'Gruntfile.js',
    'package.json',
    'bower.json',
    'requirements.txt',
    'Gemfile',
    'Gemfile.lock',
    'README.md',
    'sass',
    'js',
    'coffee',
    'env',
    'tmp'
]
